IF EXISTS ( SELECT 1 FROM	INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_SCHEMA = 'dbo' AND ROUTINE_NAME = 'spDocument_DeleteDocument' )
BEGIN
	DROP PROCEDURE [dbo].[spDocument_DeleteDocument]
END
Go

CREATE PROCEDURE [dbo].[spDocument_DeleteDocument]  
    @documentId bigint
AS  
BEGIN  
	SET NOCOUNT ON
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
	SET XACT_ABORT ON 

	BEGIN TRANSACTION
		DELETE FROM Document WHERE DocumentId = @documentId
    COMMIT TRANSACTION
END
